# Generated by Django 5.0.9 on 2024-10-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="firstname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lastname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
