# Generated by Django 5.0.9 on 2024-10-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_firstname_customuser_lastname"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="classes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hourAvailable",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weekDayAvailable",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
