# Generated by Django 5.0.9 on 2024-10-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_about_customuser_classes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="classes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Classes You Would Teach (i.e CSCI152, CSCI232, CSCI315E): ",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="hourAvailable",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Hours Available (i.e 2:00 PM - 3:00 PM): ",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weekDayAvailable",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Week Days Available (i.e. Mondays, Wednesdays, Fridays):",
            ),
        ),
    ]
